-- union all 사용 법
-- column을 맞춰서 select 값 구하는데 없는 값의 경우 null 로 맞춰주면된다.

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID,USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = "2022-03"
UNION ALL
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = "2022-03"
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC